# Site settings
baseURL = "https://griffinbrowning.com"
languageCode = "en-US"
title = "Griffin Browning"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Griffin Browning"
  description = "Graphic artist, bartender, and comedian in Columbus, OH."
  shareImage = "images/17862532_10155410675384416_6014128723221812708_n.jpg"
  twitterHandle = "griffinbrowning"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy; 2017 Griffin Browning"

  # Section - Content
  [params.content]
    name = "Griffin Browning"
    tagline = "Graphic Artist. Bartender. Comedian."
    bio = ""
    # TODO: Add a bio?
    # bio = "Donec at libero id lectus porta dapibus eu in nibh. Cras id mauris sapien. Fusce viverra [luctus urna](#) ac rutrum. Duis semper elit eu mi facilisis eleifend. Donec semper, [ipsum in](#) malesuada congue, [purus sem](#) ullamcorper massa, sit amet lacinia nibh enim sed massa."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/17862532_10155410675384416_6014128723221812708_n.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Content"

      [[params.links.list1.link]]
        text = "YouTube"
        url = "https://www.youtube.com/results?search_query=%22Griffin+Browning%22"

      [[params.links.list1.link]]
        text = "Podcast"
        url = "https://itunes.apple.com/us/podcast/filibusted!-brian-tower-doney/id1069611146"

      [[params.links.list1.link]]
        text = "Comic"
        url = "https://nocomment.jacebrowning.info"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Connect"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/griffinbrowning"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/griffinbrowning"

      [[params.links.list2.link]]
        text = "Email"
        url = "mailto:griffinbrowning@gmail.com?subject=griffinbrowning.com"

  # Links List #3
  # [[params.links]]
  #   [params.links.list3]
  #     heading = "Network"

  #     [[params.links.list3.link]]
  #       text = "Link One"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Two"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Three"
  #       url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
